name: Hello GitHub Actions

on:
  workflow_dispatch
  # push:
  #   branches:
  #     - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: 打招呼
        run: echo "Hello GitHub Actions!"
      - name: 列印日期
        run: date
      - name: 列印主機訊息
        run: |
          uname -a
          pwd
